gateway:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/target: 121.130.214.237
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - kuberca-demo.kkamji.net
  paths:
    - /
  tls:
    - secretName: kuberca-demo-tls
      hosts:
        - kuberca-demo.kkamji.net
