apiVersion: v2
name: kube-rca
description: Deploy kube-rca backend and frontend
type: application
version: 0.4.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 18.1.13
    repository: "https://charts.bitnami.com/bitnami"
