{{- if .Values.openapi.ingress.enabled -}}
{{- $ingress := .Values.openapi.ingress -}}
{{- $hosts := default (list) $ingress.hosts -}}
{{- if not (gt (len $hosts) 0) -}}
{{- fail "openapi.ingress.enabled=true requires openapi.ingress.hosts to be set" -}}
{{- end -}}
{{- $paths := default (list "/") $ingress.paths -}}
{{- $pathType := default "Prefix" $ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "kube-rca.openapi.name" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kube-rca.openapi.labels" . | nindent 4 }}
  {{- $baseAnnotations := default (dict) $ingress.annotations }}
  {{- $annotations := include "kube-rca.annotations" (dict "root" $ "component" "openapi" "annotations" $baseAnnotations) | trim }}
  {{- if $annotations }}
  annotations:
{{ $annotations | nindent 4 }}
  {{- end }}
spec:
{{- with $ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
{{- end }}
  rules:
{{- range $host := $hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
{{- range $path := $paths }}
          - path: {{ $path | quote }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ include "kube-rca.openapi.name" $ }}
                port:
                  name: http
{{- end }}
{{- end }}
{{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
