{{- if .Values.openapi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-rca.openapi.name" . }}
  labels:
    {{- include "kube-rca.openapi.labels" . | nindent 4 }}
  {{- $annotations := include "kube-rca.annotations" (dict "root" $ "component" "openapi" "annotations" (dict)) | trim }}
  {{- if $annotations }}
  annotations:
{{ $annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.openapi.service.type }}
  ports:
    - name: http
      port: {{ .Values.openapi.service.port }}
      targetPort: http
  selector:
    {{- include "kube-rca.openapi.selectorLabels" . | nindent 4 }}
{{- end -}}
