replicaCount: 1

image:
  repository: grafana/k6
  tag: "0.52.0"
  pullPolicy: IfNotPresent

# Target configuration
target:
  baseUrl: "http://productpage.bookinfo.svc.cluster.local:9080"
  detailsBaseUrl: "http://details.bookinfo.svc.cluster.local:9080"
  ratingsBaseUrl: "http://ratings.bookinfo.svc.cluster.local:9080"
  weights:
    productpage: 20
    details: 40
    ratings: 40
  rps: 100
  duration: "4h" # 4 hours (cycle via restart)
  preAllocatedVUs: 40
  maxVUs: 200

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
