{{- if .Values.ingress.enabled -}}
{{- $ingress := .Values.ingress -}}
{{- $hosts := default (list) $ingress.hosts -}}
{{- if not (gt (len $hosts) 0) -}}
{{- fail "ingress.enabled=true requires ingress.hosts to be set" -}}
{{- end -}}
{{- $paths := default (list "/") $ingress.paths -}}
{{- $pathType := default "Prefix" $ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- with $ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
{{- end }}
  rules:
{{- range $host := $hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
{{- range $path := $paths }}
          - path: {{ $path | quote }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: productpage
                port:
                  number: 9080
{{- end }}
{{- end }}
{{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
