apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-rca.agent.name" . }}
  labels:
    {{- include "kube-rca.agent.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
