apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-rca.agent.name" . }}
  labels:
    {{- include "kube-rca.agent.labels" . | nindent 4 }}
  {{- $annotations := include "kube-rca.annotations" (dict "root" $ "component" "agent" "annotations" (dict)) | trim }}
  {{- if $annotations }}
  annotations:
{{ $annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-rca.agent.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-rca.agent.name" . }}
    namespace: {{ .Release.Namespace }}
