{{- if .Values.agent.ingress.enabled -}}
{{- $ingress := .Values.agent.ingress -}}
{{- $hosts := default (list) $ingress.hosts -}}
{{- if not (gt (len $hosts) 0) -}}
{{- fail "agent.ingress.enabled=true requires agent.ingress.hosts to be set" -}}
{{- end -}}
{{- $paths := default (list "/") $ingress.paths -}}
{{- $pathType := default "Prefix" $ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "kube-rca.agent.name" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kube-rca.agent.labels" . | nindent 4 }}
{{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- with $ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
{{- end }}
  rules:
{{- range $host := $hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
{{- range $path := $paths }}
          - path: {{ $path | quote }}
            pathType: {{ $pathType }}
            backend:
              service:
                name: {{ include "kube-rca.agent.name" $ }}
                port:
                  name: http
{{- end }}
{{- end }}
{{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
