apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-rca.agent.name" . }}
  labels:
    {{- include "kube-rca.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.agent.service.type }}
  selector:
    {{- include "kube-rca.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  ports:
    - name: http
      port: {{ .Values.agent.service.port }}
      targetPort: http
